server:
  port: 8084
  servlet:
    session:
      cookie:
        name: GATEWAYSERVERSESSION
spring:
  application:
    name: gateway-service
    port: 8084
  cloud:
    gateway:
      server:
        webflux:
          routes[0]:
            id: user-service
            uri: http://user-service:8080
            predicates[0]: Path=/api/v1/users/** ,/api/v1/cards/**
            filters[0]: TokenRelay=
          routes[1]:
            id: auth-service
            uri: http://auth-service:8082
            predicates[0]: Path=/api/v1/authorization/**
            filters[0]: TokenRelay=
          routes[2]:
            id: order-service
            uri: http://order-service:8083
            predicates[0]: Path=/api/v1/orders/**, /api/v1/items/**, /api/v1/ordered-items/**
            filters[0]: TokenRelay=
          routes[3]:
            id: oauth
            uri: http://auth-service:8082
            predicates[0]: Path=/auth-server/**
            filters[0]: RewritePath=/auth-server/(?<remaining>.*), /$\{remaining}
            filters[1]: TokenRelay=
          routes[4]:
            id: payment-service
            uri: http://payment-service:8085
            predicates[0]: Path=/api/v1/payments/**
            filters[0]: TokenRelay=

  security:
    oauth2:
      client:
        registration:
          my-oidc-client:
            provider: my-oidc-provider
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          my-oidc-provider:
            issuer-uri: http://auth-service:8082
            authorization-uri: http://auth-service:8082/oauth2/authorize
            token-uri: http://auth-service:8082/oauth2/token
            redirect-uri: http://gateway-service:8084/login/oauth2/code/my-oidc-client
            user-info-uri: http://gateway-service:8084/auth-server/oauth2/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://gateway-service:8084/auth-server/oauth2/jwks
signup:
  external:
    uri:
      auth-server-create: http://auth-service:8082/api/v1/authorization/create
      auth-server-delete: http://auth-service:8082/api/v1/authorization/delete
      user-service-create: http://user-service:8080/api/v1/users/create
    param:
      auth-server-delete: code
    backoff-delay: 2
    max-attempts: 3

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    oauth:
      client-id: gateway-client
      use-pkce-with-authorization-code-grant: false
    oauth2-redirect-url: http://gateway-service:8084/swagger-ui/oauth2-redirect.html
  oAuthFlow:
    authorizationUrl: http://auth-service:8082/oauth2/authorize
    tokenUrl: http://auth-service:8082/oauth2/token
    scopes: openid
swagger-server: http://gateway-service:8084/