server:
  port: ${PORT}
  servlet:
    session:
      cookie:
        name: GATEWAYSERVERSESSION
spring:
  profiles:
    default: ${SPRING_PROFILE}
  application:
    name: gateway-service
    port: ${PORT}
  cloud:
    gateway:
      server:
        webflux:
          routes[0]:
            id: user-service
            uri: ${USER_SERVICE_ADDR}
            predicates[0]: Path=/api/v1/users/** ,/api/v1/cards/**
            filters[0]: TokenRelay=
          routes[1]:
            id: auth-service
            uri: ${AUTH_SERVICE_ADDR}
            predicates[0]: Path=/api/v1/authorization/**
            filters[0]: TokenRelay=
          routes[2]:
            id: order-service
            uri: ${ORDER_SERVICE_ADDR}
            predicates[0]: Path=/api/v1/orders/**, /api/v1/items/**, /api/v1/ordered-items/**
            filters[0]: TokenRelay=
          routes[3]:
            id: oauth
            uri: ${AUTH_SERVICE_ADDR}
            predicates[0]: Path=/auth-server/**
            filters[0]: RewritePath=/auth-server/(?<remaining>.*), /$\{remaining}
            filters[1]: TokenRelay=
          routes[4]:
            id: payment-service
            uri: ${PAYMENT_SERVICE_ADDR}
            predicates[0]: Path=/api/v1/payments/**
            filters[0]: TokenRelay=

  security:
    oauth2:
      client:
        registration:
          my-oidc-client:
            provider: my-oidc-provider
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          my-oidc-provider:
            issuer-uri: http://${AUTH_HOST_PORT}
            authorization-uri: http://${AUTH_HOST_PORT}/oauth2/authorize
            token-uri: http://${AUTH_HOST_PORT}/oauth2/token
            redirect-uri: http://${GATEWAY_HOST_PORT}/login/oauth2/code/my-oidc-client
            user-info-uri: http://${GATEWAY_HOST_PORT}/auth-server/oauth2/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://${GATEWAY_HOST_PORT}/auth-server/oauth2/jwks
signup:
  external:
    uri:
      auth-server-create: http://${AUTH_HOST_PORT}/api/v1/authorization/create
      auth-server-delete: http://${AUTH_HOST_PORT}/api/v1/authorization/delete
      user-service-create: http://${USER_HOST_PORT}/api/v1/users/create
    param:
      auth-server-delete: code
    backoff-delay: 2
    max-attempts: 3

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    oauth:
      client-id: gateway-client
      use-pkce-with-authorization-code-grant: false
    oauth2-redirect-url: http://${GATEWAY_HOST_PORT}/swagger-ui/oauth2-redirect.html
  oAuthFlow:
    authorizationUrl: http://${AUTH_HOST_PORT}/oauth2/authorize
    tokenUrl: http://${AUTH_HOST_PORT}/oauth2/token
    scopes: openid
swagger-server: http://${GATEWAY_HOST_PORT}/
logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      springframework:
        security: TRACE
        cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE


management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector.monitoring.svc.cluster.local:4318
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: "always"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

otel:
  traces:
    sampler: always_on
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://otel-collector.monitoring.svc.cluster.local:4317