apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service-container
          image: gateway-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
          env:
          - name: SPRING_PROFILE
            value: prod
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-client-secrets
                key: client-id
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-client-secrets
                key: client-secret

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  tls:
    - hosts:
        - "auth-service"
      secretName: tls-secret-auth
  rules:
    - host: auth-service
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 443